export const COUNTER_INCREMENT = 'COUNTER INCREMENT';
export const COUNTER_DECREMENT = 'COUNTERDECREMENT';
export const COUNTER_RESET     = 'COUNTER RESET';
export const OPEN_DIALOGUE     = 'OPEN DIALOGUE';
export const CLOSE_DIALOGUE    = 'CLOSE DIALOGUE';